#spring:
#  cloud:
#    openservicebroker:
#      Open Service Broker configuration properties are configured test setup
#    appbroker:
#      services:
#        App Broker services configuration properties are configured individual test cases
#      deployer:
#        App Broker deployer configuration properties are configured test setup

logging:
  level:
    cloudfoundry-client: DEBUG
    org.springframework.cloud.appbroker: DEBUG
spring:
  credhub:
    url: https://credhub.service.cf.internal:8844
  application:
    name: sample-broker
